name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        host:
          - vim_type: Vim
            version: head
          - vim_type: Vim
            version: v8.1.2424
          - vim_type: Neovim
            version: head
          - vim_type: Neovim
            version: v0.4.3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_type: ${{ matrix.host.vim_type }}
          vim_version: ${{ matrix.host.version }}
      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis
